### ISSUE TITLE
image gcr.io/google-samples not accessible

### ISSUE THREAD

**Issue by jakob-christian-auticon** [radius-project/samples#959] opened 2024-02-01 14:23 UTC
### Steps to reproduce

If I follow the Tutorial 'Existing Application' [link](https://docs.radapp.io/tutorials/add-radius/)

### Observed behavior

At step 2.2: verify the successful app deployment
There are some errors regarding the pods using the gcr.io/google-samples images  are shown:
 ```
NAME                                 READY   STATUS             RESTARTS      AGE
pod/frontend-69b9556bc-6jbk5         0/1     ImagePullBackOff   0             11m
pod/frontend-69b9556bc-95pxl         0/1     ImagePullBackOff   0             11m
pod/frontend-69b9556bc-pxkhs         0/1     ImagePullBackOff   0             11m
pod/redis-master-56bdd57d44-wnh49    1/1     Running            0             11m
pod/redis-replica-749c7957c4-9nktk   0/1     CrashLoopBackOff   7 (38s ago)   11m
pod/redis-replica-749c7957c4-q9hrd   0/1     CrashLoopBackOff   7 (52s ago)   11m
```
### Desired behavior

images are pulled and usable

### Workaround

I exchanged the image URL using this list [synced images](https://github.com/Doublemine/gcr.io-mirror/blob/master/google-samples.md)

### rad Versoion

RELEASE   VERSION   BICEP     COMMIT
0.29.0    v0.29.0   0.29.0    6abd7bfc3de0e748a2c34b721d95097afb6a2bba

### kubernetes
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1

inside Docker Desktop 4.27.0 (135262)

### OS

WinOS 11

[AB#11078](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11078)

**Comment by shalabhms** [comment] 2024-02-01 20:52
Duplicate of https://github.com/radius-project/samples/issues/914

**Closed as not planned** 2024-03-27 21:12 UTC
