### ISSUE TITLE
Flaky test - "Failed to load resource: net::ERR_NAME_NOT_RESOLVED"

### ISSUE THREAD

**Issue by vinayada1** [radius-project/samples#956] opened 2024-01-31 19:22 UTC
Running 3 tests using 1 worker
Error text: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Error text: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Error text: "[2024-01-31T15:49:57.027Z] Error: Failed to complete negotiation with the server: Error"
Error text: "[2024-01-31T15:49:57.027Z] Error: Failed to start the connection: Error"
Error text: "Failed to load resource: net::ERR_NAME_NOT_RESOLVED"
Error text: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
Error text: "ERROR TypeError: Cannot read properties of null (reading 'message')

[AB#11064](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11064)

**Comment by vinayada1** [comment] 2024-01-31 19:23
Test logs: [logs_7537.zip](https://github.com/radius-project/samples/files/14116180/logs_7537.zip)

**Comment by ytimocin** [comment] 2024-04-25 23:31
Duplicate of #1030.

**Closed as completed by ytimocin** 2024-04-25 23:31 UTC
Labels: triaged, flaky-test, maintenance
