### ISSUE TITLE
Functional Test Failure: eshop azure: System.IO.IOException: Unable to read data from the transport connection

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/samples#893] opened 2023-12-06 03:02 UTC
Functional test error when running samples https://github.com/radius-project/samples/actions/runs/7104964592: 
<img width="1283" alt="image" src="https://github.com/radius-project/samples/assets/103459615/9faf3927-be74-4b60-8708-367bbf2fbb9b">

[logs_6966.zip](https://github.com/radius-project/samples/files/13574462/logs_6966.zip)

Going through the logs, earlier error indicates:
```
{
2023-12-05T18:28:02.6968102Z                           "code": "ResourceDeploymentFailure",
2023-12-05T18:28:02.6989589Z                           "message": "An exception was encountered. Current deployment operation has failed. Error message: 'An error occurred while sending the request.'. Exception: 'System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.\n ---\u003e System.Net.Sockets.SocketException (104): Connection reset by peer\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)\n   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)\n   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)\n   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)\n   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\n   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()\n   at System.Threading.Thread.StartCallback()\n--- End of stack trace from previous location ---\n\n   --- End of inner exception stack trace ---\n   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)\n   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)\n   at System.Net.Http.HttpConnection.\u003cCheckUsabilityOnScavenge\u003eg__ReadAheadWithZeroByteReadAsync|45_0()\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)'",
2023-12-05T18:28:02.7002850Z                           "target": "/subscriptions/***/resourceGroups/rg-samplestest-7104964592-1-eshop-azure/providers/Microsoft.Sql/locations/westus3/serverOperationResults/599b5af1-380a-4dbe-a168-799d4824fabc"
2023-12-05T18:28:02.7003923Z                         }
```

This was reported during functional test run : https://github.com/radius-project/samples/issues/891

Note: The artifact for eshop azure was not created during this run/errored out before artifact was created : https://github.com/radius-project/samples/actions/runs/7104964592 . Determine if this is expected or no.

[AB#10669](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10669)

**Comment by ytimocin** [comment] 2024-04-25 23:49
I haven't run into this issue within the last few weeks I have been working on the tests. This is also caused by the other end as you can see from the message `Connection reset by peer`. Closing this for now.

**Closed as completed by ytimocin** 2024-04-25 23:49 UTC
Labels: triaged, important, test-failure
