### ISSUE TITLE
Flaky test: `Failed to load resource: Message Corrupt`

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/samples#883] opened 2023-11-28 19:18 UTC
I have seen this happen occasionally in CI with each of our playwright tests.

```
Running 3 tests using 1 worker
×××F×××FError text: "Failed to load resource: Message Corrupt"
×Error text: "Failed to load resource: Message Corrupt"
×Error text: "Failed to load resource: Message Corrupt"
×Error text: "Failed to load resource: Message Corrupt"
F
```

[AB#10573](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10573)

**Comment by kachawla** [comment] 2024-01-11 18:39
Another failure caused by this issue: https://github.com/radius-project/samples/issues/929
Link to the workflow run: https://github.com/radius-project/samples/actions/runs/7491144290/job/20391662217

**Comment by vinayada1** [comment] 2024-02-01 19:04
Seen multiple of these failures during runs for the 0.30.0-rc3 release

**Comment by ytimocin** [comment] 2024-05-06 16:13
Closing this for now as we need more information. Will keep an eye on this specific error message and reopen if necessary.

**Closed as completed by ytimocin** 2024-05-06 16:13 UTC
Labels: triaged, important, test-failure, flaky-test
