### ISSUE TITLE
Improve reliability of playwright tests

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/samples#1018] opened 2024-03-19 21:16 UTC
We have seen some issues with the playwright tests with network issues.

https://github.com/radius-project/samples/issues/885
https://github.com/radius-project/samples/issues/883
https://github.com/radius-project/samples/issues/907

We should consider improving the reliability of these tests through retries, better logging, etc.

[AB#11555](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11555)

**Comment by youngbupark** [comment] 2024-03-20 22:31
The major failure happens only when eshop is being deployed to k3d cluster. testing it on EKS cluster is always stable. My hypothesis is that it might be related to resource constraints of single vm cluster. I would check whether the root cause of this problem stems from resource limitation or not by switching k3d cluster to aks cluster and running it for at least a week.

**Comment by ytimocin** [comment] 2024-03-20 23:09
I will schedule a meeting with you, @youngbupark and @willdavsmith. We can discuss about these flaky tests. I am also working on a task right now which is also related to this.

**Comment by ytimocin** [comment] 2024-05-06 16:10
I have added retries, better logging, and improved the workflows. I added the video recordings of the failure and changed the readiness checks to liveness checks. I am closing this for now and, going forward, we can focus on the issues that pop up in the tests.

**Closed as completed by ytimocin** 2024-05-06 16:10 UTC
Labels: triaged, important
