### ISSUE TITLE
[Regression] Improve reliability for DNS-SD change

### ISSUE THREAD

**Issue by youngbupark** [radius-project/samples#1040] opened 2024-04-03 20:03 UTC
## Problem

This is the regression bug after we merge [this PR](https://github.com/radius-project/samples/pull/574) to use DNS-SD.

```
We have to fix the tests, so that it works with new DNS-SD based eshop.
Since we removed HTTPRoutes, there is more parallelization and the deployment is ready after a few seconds of printing out the success message.
The tests always pass the second time.

Web application is ready: http://localhost/
Error text: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Error text: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Error text: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
Error text: "[2024-03-23T15:50:44.663Z] Error: Failed to complete negotiation with the server: Error"
Error text: "[2024-03-23T15:50:44.666Z] Error: Failed to start the connection: Error"
Error text: "Failed to load resource: net::ERR_NAME_NOT_RESOLVED"
```

## Related issues
https://github.com/radius-project/samples/issues/1022
https://github.com/radius-project/samples/issues/1025
https://github.com/radius-project/samples/issues/1021

[AB#11694](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11694)

**Comment by youngbupark** [comment] 2024-04-03 20:04
@nithyatsu I created the separate issue for the regression after we removing httproute.

**Comment by sylvainsf** [comment] 2024-04-04 19:44
@nithyatsu Can you please look into this?

**Comment by nithyatsu** [comment] 2024-04-08 15:38
I am looking into this, but I don't seem to have permissions to assign the issue to myself @sylvainsf

**Comment by nithyatsu** [comment] 2024-04-08 16:06
This seemed like a regression to me initially, but it is not, since I see the same issue logged by @vinayada1 sometime last year november. https://github.com/radius-project/samples/issues/885 @youngbupark  @sylvainsf

**Comment by willdavsmith** [comment] 2024-04-24 17:04
Closing in favor of https://github.com/radius-project/samples/issues/885

**Closed as completed by willdavsmith** 2024-04-24 17:04 UTC
Labels: triaged, bug, flaky-test
