### ISSUE TITLE
Failed by `Container are not ready`

### ISSUE THREAD

**Issue by youngbupark** [radius-project/samples#1042] opened 2024-04-03 20:17 UTC
## Problem

`Wait for all pods to be ready` step is failing. This has 90s timeout for pods ready check. We might need to increase the timeout. This happened only in eshop-azure test. Also it might be related to the limited resource of the cluster.

```
Run namespace="azure-eshop"
  namespace="azure-eshop"
  label="radapp.io/application=eshop"
  kubectl rollout status deployment -l $label -n $namespace --timeout=90s
  shell: /usr/bin/bash -e {0}
  env:
    RUN_IDENTIFIER: samplestest-849179363[2](https://github.com/radius-project/samples/actions/runs/8491793632/job/23264109576#step:19:2)-1
    BRANCH: v0.32
    GH_TOKEN: ***
    AZURE_LOCATION: westus[3](https://github.com/radius-project/samples/actions/runs/8491793632/job/23264109576#step:19:3)
    AWS_REGION: us-west-2
    AWS_ZONES: us-west-2a,us-west-2b,us-west-2c
deployment "webstatus" successfully rolled out
deployment "seq" successfully rolled out
deployment "webshoppingapigw" successfully rolled out
Waiting for deployment "webshoppingagg" rollout to finish: 0 of 1 updated replicas are available...
deployment "payment-api" successfully rolled out
deployment "webhooks-client" successfully rolled out
deployment "ordering-api" successfully rolled out
deployment "ordering-backgroundtasks" successfully rolled out
deployment "webhooks-api" successfully rolled out
deployment "catalog-api" successfully rolled out
deployment "basket-api" successfully rolled out
deployment "web-spa" successfully rolled out
deployment "webmvc" successfully rolled out
deployment "ordering-signalrhub" successfully rolled out
deployment "identity-api" successfully rolled out
error: timed out waiting for the condition
Error: Process completed with exit code 1.
```

## Test failure links

https://github.com/radius-project/samples/issues/1034
https://github.com/radius-project/samples/issues/1035

[AB#11698](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11698)

**Comment by sylvainsf** [comment] 2024-04-04 19:48
@ytimocin can you increase the value and we can see if it's resolved?

**Comment by ytimocin** [comment] 2024-04-25 23:32
Duplicate of #1057.

**Closed as completed by ytimocin** 2024-04-25 23:32 UTC
Labels: triaged, bug, flaky-test
